#!/usr/bin/with-contenv bash
set -e

mkdir -p /config/logs/code-server
chown abc:abc /config/logs/code-server

exec s6-setuidgid abc \
    /app/code-server/lib/node /app/code-server \
    --bind-addr "[::]:8443" \
    --user-data-dir /config/data \
    --extensions-dir /config/extensions \
    --disable-telemetry \
    --auth none \
    --app-name code-server \
    /config/workspace \
    >>/config/logs/code-server/code-server.log 2>&1
