#!/usr/bin/with-contenv bash
set -e

mkdir -p /config/logs/nginx
touch /config/logs/nginx/nginx.pid
chown root:root /config/logs/nginx/nginx.pid

exec nginx -c /config/nginx/nginx.conf -g "daemon off;"
