#!/usr/bin/with-contenv bash
set -e

mkdir -p \
    /config/app \
    /config/www \
    /config/mongo_data \
    /config/logs/nginx \
    /config/logs/mongodb \
    /config/logs/code-server \
    /config/nginx \
    /config/.pm2

if [ ! -f /config/app/server.js ]; then
    cp /opt/default-node-app.js /config/app/server.js
fi

if [ ! -f /config/app/package.json ]; then
    cp /opt/default-express-package.json /config/app/package.json
fi

if [ ! -f /config/app/ecosystem.config.js ]; then
    cp /opt/default-ecosystem.config.js /config/app/ecosystem.config.js
fi

if [ ! -f /config/www/index.html ]; then
    cp /opt/default-index.html /config/www/index.html
fi

if [ ! -f /config/nginx/nginx.conf ]; then
    cp /opt/default-nginx.conf /config/nginx/nginx.conf
fi

chown -R abc:abc \
    /config/app \
    /config/www \
    /config/mongo_data \
    /config/logs \
    /config/nginx \
    /config/.pm2 \
    /config/app \
    /config/www

nginx -t -c /config/nginx/nginx.conf
